<style type="text/css">
    h1 {
        margin-top:0;
    }
    .form-fieldsets {
        margin-left:30px;
    }
    .form-fieldsets h2 {
        margin-left:-10px;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $('.agreement').bind('click',function(e){
            e.preventDefault();
            agreementwindow = new RichHTML.window({
                height: '400',
                width: '550',
                url: 'plugins/snapin/opensrsform/Services_Agreement.html',
                title: "Services Agreement"
            });
            agreementwindow.show();
        });
    })
</script>

<div class="alert ce-alert ce-alert-error" style="<?php echo (!isset($this->ERR) || trim($this->ERR) == "") ? "display:none;" :"" ?>">
    <a class="close" data-dismiss="alert">×</a>
    <?php echo $this->ERR; ?>
</div>

<?php if ( isset($this->successMessage) ) { ?>
    <div class="alert ce-alert ce-alert-success">
        <a class="close" data-dismiss="alert">×</a>
        <?php echo $this->unescape($this->successMessage); ?>
    </div>
<?php  } ?>

<h1><?php echo $this->user->lang("Create your OpenSRS reseller account");?></h1>

<div class="alert ce-alert ce-alert-info" style="<?php echo (!isset($this->snapinHeader) || trim($this->snapinHeader) == "") ? "display:none;" :"" ?>">
    <?php echo $this->snapinHeader; ?>
</div>

<form method='post' action='index.php?fuse=admin&action=snapin&controller=snapins&plugin=opensrsform&v=view'>

    <div class="form-fieldsets">

        <h2><?php echo $this->user->lang('Contact Information'); ?></h2>

        <div class="row">
            <fieldset class="ce-fieldset">
            <label><?php echo $this->user->lang("Organization");?></label>
            <input type="text"  name="org_name" id="org_name"  value="<?php echo $this->organization; ?>" />
            </fieldset>
        </div>

        <div class="row">
            <fieldset class="ce-fieldset">
            <label><?php echo $this->user->lang('First Name'); ?></label>
            <input  type="text" name="first_name" id="first_name" value="<?php echo $this->firstName; ?>" />
            </fieldset>

            <fieldset class="ce-fieldset">
            <label><?php echo $this->user->lang('Last Name'); ?></label>
            <input  type="text" name="last_name" id="last_name" value="<?php echo $this->lastName; ?>" />
            </fieldset>

            <fieldset class="ce-fieldset">
            <label><?php echo $this->user->lang('Email'); ?></label>
            <input  type="text" name="email" id="email" value="<?php echo $this->email; ?>" />
            </fieldset>
        </div>

        <div class="row">
            <fieldset class="ce-fieldset">
                <label><?php echo $this->user->lang("Address Line");?></label>
                <input type="text"  name="address1" id="address1"  value="<?php echo $this->address; ?>" />
            </fieldset>
        </div>


        <div class="row">
            <fieldset class="ce-fieldset">
                <label><?php echo $this->user->lang('City'); ?></label>
                <input  class="input-mini" type="text" name="city" id="city" value="<?php echo $this->city; ?>" />
            </fieldset>

            <fieldset class="ce-fieldset">
                <label><?php echo $this->user->lang('State'); ?></label>
                <input  class="input-medium" type="text" name="state" id="state" value="<?php echo $this->state; ?>" />
            </fieldset>

            <fieldset class="ce-fieldset">
                <label><?php echo $this->user->lang('Country'); ?></label>
                <select name="country" id="country" >
                    <?php echo $this->unescape($this->countries);?>
                </select>
            </fieldset>

            <fieldset class="ce-fieldset">
                <label><?php echo $this->user->lang('Zip Code'); ?></label>
                <input  class="input-medium" type="text" name="postal_code" id="postal_code" value="<?php echo $this->zipcode; ?>" />
            </fieldset>
        </div>

        <div class="row">
            <fieldset class="ce-fieldset">
                <label><?php echo $this->user->lang("Phone");?></label>
                <input type="text"  name="phone" id="phone"  value="<?php echo $this->phone; ?>" />
            </fieldset>

            <fieldset class="ce-fieldset">
                <label><?php echo $this->user->lang("Fax");?></label>
                <input type="text"  name="fax" id="fax"  value="" />
            </fieldset>
        </div>

        <hr style="margin-top:10px;margin-bottom:10px;color:#eee;width:400px;" />

        <h2><?php echo $this->user->lang('Security Information'); ?></h2>

        <div class="row">
            <fieldset class="ce-fieldset">
                <label><?php echo $this->user->lang('Preferred Username'); ?></label>
                <input  type="text" name="username" id="username" value="<?php echo $this->id; ?>" />
            </fieldset>

            <fieldset class="ce-fieldset">
                <label><?php echo $this->user->lang('Password'); ?></label>
                <input  type="text" name="password" id="password" value="<?php echo $this->pw; ?>" />
            </fieldset>

        </div>

        <div class="row">
            <fieldset class="ce-fieldset">

                <label class="checkbox">
                  <input type="checkbox" name="agree" /> <a class="agreement" href="#"gu>Agree to the TUCOWS master services agreement</a>
                </label>

            </fieldset>
        </div>
    </div>

    <div class="form-actions">
        <input type="submit" class="btn" name="submit" value='<?php echo $this->user->lang("Submit Application");?>' />
    </div>