<style>
    .licensedetails label {
        display: inline;
        color: green;
        font-weight: bold;
        padding-left: 15px;
    }

    .licensedetails {
        padding-left: 21px;
        padding-bottom: 10px;
    }
    .detailheader {
        padding-top: 10px;
        font-weight: bold;
        padding-left: 15px;
        margin-bottom: -10px;
    }
</style>

<ul class="nav nav-tabs">
    <?php $url = 'index.php?fuse=admin&view=viewsnapin&controller=snapins&plugin=licensedefender&v=resellers'; ?>
    <li id="" class="active">
        <span>Licenses</span>
    </li>
    <li id="tab_Resellers" style="display:none;">
        <span class="clickable-link" data-url="<?php echo $url;?>">Resellers</span>
    </li>
</ul>

<div class="alert alert-info" style="margin-bottom:5px;">
    <span  style="color:black;font-size: 13px;">Username: <a style='cursor:pointer' title="Remove all filters" onclick='licensedefender.removeAllFilters();'><?php echo $this->username; ?></a></span>
    <span id="loggedinas" style="color:gray;font-size: 13px;"></span>
    <span id="searchkey" style="font-size: 13px;padding-right:3px;"></span>
    <span id="totallicenses" style="display:none;">
        <span style="color: rgb(231, 255, 223);"> | </span>
        Allotted (<span id="totallicenses_count">NA</span>)
    </span>
    <span id="usedlicenses">
        <span style="color: rgb(231, 255, 223);"> | </span>
        Assigned (<span id="usedlicenses_count">NA</span>)
    </span>

    <span id="remaininglicenses" style="display:none;">
    <span style="color: rgb(231, 255, 223);"> | </span>
        Remaining (<span id="remaininglicenses_count">NA</span>)
    </span>
    <div style="float:right; margin-right: -30px;font-size: 12px;position:relative;top:-5px;font-weight: bold;">
        Search: <input type="text"  value="" onkeydown="if(event.keyCode==13) licensedefender.searchLicense();" id="searchlicense" name="searchlicense" />&nbsp;&nbsp;&nbsp;
    </div>
</div>

<span class="grid-meta" id="resellerPanel-grid-metadata"></span>
<div id="gridheader" class="blue-box">
    <table class="automation">
        <tbody>
            <tr>
            	<td><button id="addButton" class="rich-button"><span id="addButtonText"><?php echo $this->user->lang("Add License(s)");?></span></button></td>
                <td align="right" id="resellerLabel" style="display: none">
                    <?php echo $this->user->lang("Reseller");?>:
                    &nbsp;&nbsp;
                </td>
                <td align="left" style="width:150px; display: none" id="resellerSelect">
                    <select class="dropdown-select" style="width:140px;" id='resellerPanel-grid-filterbystatus'>
                        <option value="all">All</option>
                        <?php foreach ( $this->resellerNames as $reseller ) { ?>
                        <option value="<?php echo $reseller['username']; ?>"><?php echo $reseller['username']; ?></option>
                        <?php } ?>
                    </select>
                </td>
                <td align="left" style="width:60px">
                    <select id='resellerPanel-grid-filter' class="change-grid-showrecords" style='width:60px;'><option value='5'>5</option><option value='10'>10</option><option value='25'>25</option><option value='50'>50</option><option value='150'>150</option><option value='300'>300</option></select>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div id="resellerPanel-grid"></div>
<div id="resellerPanel-grid-footer" style="display:none;">
    <button class="rich-button" id="deleteButton"><span><?php echo $this->user->lang("Delete License(s)"); ?></span></button>
</div>